---
  - name: APT | Install DotDeb key
    apt_key: >
      url=http://www.dotdeb.org/dotdeb.gpg
      state=present

  - name: APT | Add DotDeb wheezy repository
    apt_repository: >
      repo='$item'
      state=present
      update_cache=yes
    with_items:
      - deb http://packages.dotdeb.org wheezy all
      - deb-src http://packages.dotdeb.org wheezy all
      - deb http://packages.dotdeb.org wheezy-php55 all
      - deb-src http://packages.dotdeb.org wheezy-php55 all
